language: python
dist: trusty
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python spec/tests_net.py
deploy:
  provider: heroku
  app: net-positive
  api_key:
    secure: ecHAbFdJnyYcXPUWMAZkqiNQfd/i1PARI1olY42tpLHXHSampAv1Rb44UbyJhLBlRe14UZyaBZ8qnxDeiKEPROXhE4CI685nwWkM4mP/98wqoE6CkCmB8K+pEIaKx0RLVbqL7CqnNI1wFkUzcCJIR2HlYjBgppn42AvUaZ6NreX1ZU2iYmw5Jo6RRDBAIBspaPN2gTv1DPJLBWUi+ZJN8CPPD8LtM8QWd394Gg5nOttBRfLSX+Jez79jEGF7FVUlUNg18Cll1SnFInQY9I8UgtYhlVOVe8a4jE/ZrR9YhLSwpImpP8eWzhvwERyiVJrWvyhrNWpPkqBbmhg5rlc2KYAiOiBqb2oWuKcZ4EI2rc6tKsyTfs40ljLr4HNKoKijD5BNG7ltvjnuK7V6yBEfWWgz87AjwyTaRut+IR8f9M49gfrPu+sc+CACf1cOdVlOhITjwuhbkuUur3PnkMReNaYwkHpl/ODyjIEKvff5cmCRywOvj+69eT9AAmmLlZ4liyDwflWCGnroXU2WkEmIkcqo2Y64yZOVeq5dK4yRpyjBnxtgRBWpQ6grCn9Z9C5oefEJe0fefQvCV0ZNJYGPua9BzPLvVOSPK7VFtbYnicOkPro4uMQoOYR9/8RAIbIfLUmDzlBAgncI1RnpwdwujXpDrAclNBe3FQLZx/Fjnd8=
