language: python
dist: trusty
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python spec/tests_net.py
deploy:
  provider: heroku
  app: net-positive
  api_key:
    secure: gJIMoejVcatoF28vnEQ33KCmKPnLCez8++V9ofNJIF//vn8KakJUm1ufNy/k5I0DreAeNrjo6HUXLYxdtgsCegEMW/UfUVuKPwq2rXgThCAAi/3hUupREfcCtcYRwghEmR0oEyI0Nye0gim58Q1n3pnBbB1S87BcOc6fKkba2a+79UWRcRL9M7yiwN9LXcd4N8NJI7cejkColnSi+oOtrsPUMIyaFEM4BETG1BraiOfrsqa8zxY/Qld4oPvrUKxiPKQ1M3cnWzaIOnWR7dtNHFE858beZc05KU2/X74k7rg6fp6KCFGOja0226uujOEhgcghph89H24Usx6Z68hqeDJ0ZI48CnuHRD3aoix20monMLIr0iErUu4nqT6W10RGjIdi1tI8MDUHHh+6DtUS8XpVN22gMfFj0ZNByJfs5ERfM2NwVc8q3MBMt8c53K9Yry9Y0mUQ5lIBjZST8lKckyU3WgbEqcF/orYR+EOY5tdokzND50Hn66PsgCvPrDhP3mLbic95RlVW/a+g4Y1fFvm6ewTvUqxrzccw/Ml/QGV7cSQHaJ5/jsuLtgsJeZD5ojGvN7MxSXNXVlVlswKCCMDOB9/PENaUkaUwGhbbcWjkgYiT/ufJev5UIBG1c5QAWSlPsIHZnQyQVGlVVbiaTBURjI+98RNdTFAN6vn5Wvk=
